### PR TITLE
Add support for Nautilus 43 and some other patches

### PR DESCRIPTION
**Pull request by ArtyIF**
Also removes support for earlier versions. I'm planning to add it back in some way, this is why this PR is tagged as draft in the meantime

### CODE REVIEW

**Comment by ArtyIF** [comment]
Added support for older versions back (hopefully)

**Comment by ppvan** [comment]
I'm not familiar with gtk that much.
Actually I'm not using GNOME 43 now, so feel free to add new support

**Comment by ArtyIF** [comment]
> I'm not familiar with gtk that much. Actually I'm not using GNOME 43 now, so feel free to add new support

Already done. I'm daily-driving this version. The only concern of mine is compatibility with GNOME 42 or less

**Comment by ppvan** [comment]
Ok, should i merge this now?

**Comment by ArtyIF** [comment]
Yes, go ahead

**Pull request merged**
